### ISSUE TITLE
Problems in adjusting model resolution

### ISSUE THREAD

**Issue by 1378dm** [eps696/stylegan2#5]
I had some problems trying to use `model_convert.bat` to adjust the resolution of the trained non square model. I can't solve it.
This is my input on the console:

> model_convert.bat ./models/test1_final.pkl --res 1536-1024

This is the output of the console:

> Loading model ./models/test1_final.pkl
 Reconstructing model with size [1024, 1536]
[                                                  ] 0/138, elapsed: 0s, ETA:
Start...
Traceback (most recent call last):
  File "src/model_convert.py", line 203, in <module>
    main()
  File "src/model_convert.py", line 178, in main
    copy_and_crop_trainables(G_in, G_out)
  File "src/model_convert.py", line 146, in copy_and_crop_trainables
    tgt_net.set_var(target_name, update)
  File "C:\Users\vipuser\Desktop\stylegan2-master\src\dnnlib\tflib\network.py", line 264, in set_var
    tfutil.set_vars({self.find_var(var_or_local_name): new_value})
  File "C:\Users\vipuser\Desktop\stylegan2-master\src\dnnlib\tflib\tfutil.py", line 218, in set_vars
    run(ops, feed_dict)
  File "C:\Users\vipuser\Desktop\stylegan2-master\src\dnnlib\tflib\tfutil.py", line 31, in run
    return tf.get_default_session().run(*args, **kwargs)
  File "C:\Users\vipuser\AppData\Local\Programs\Python\Python37\lib\site-packages\tensorflow\python\client\session.py", line 950, in run
    run_metadata_ptr)
  File "C:\Users\vipuser\AppData\Local\Programs\Python\Python37\lib\site-packages\tensorflow\python\client\session.py", line 1149, in _run
    str(subfeed_t.get_shape())))
ValueError: Cannot feed value of shape (1, 512, 4, 3) for Tensor 'G_synthesis_2/4x4/Const/const/new_value:0', which has shape '(1, 512, 4, 6)'

The original resolution of the model is 1024 * 1536.
Can you help me solve this problem?

**Comment by eps696** [comment]
it seems you use some old version of this repo, without padding functionality (you can check the lines from the output - they're different from the current code). update it, should work.

**Comment by 1378dm** [comment]
Yes, when I updated repo, this problem did not recur.
